### ISSUE TITLE
python3 manage.py collectstatic出错

### ISSUE THREAD

**Issue by ohyeah521** [1251240000/StcokVisualization#4]
```
root@13121212:~/StcokVisualization# python3 manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 343, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 249, in delete_file
    if self.storage.exists(prefixed_path):
  File "/usr/local/lib/python3.7/dist-packages/django/core/files/storage.py", line 308, in exists
    return os.path.exists(self.path(name))
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/storage.py", line 43, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

**Comment by ohyeah521** [comment]
解决方法：

在settings.py中增加

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
